CREATE DATABASE ALKAHALI
USE ALKAHALI

CREATE TABLE EMPLOYEE (
  SSN int PRIMARY KEY,
  Fname varchar(50),
  Lname varchar(50),
  BD DATE NOT NULL,
  gender varchar(20),
  );

  CREATE TABLE DEPARTMENT (
  DNUM int PRIMARY KEY,
  Dname varchar(5),
  hiredate DATE NOT NULL,
  );

  CREATE TABLE DEPTLOCATION (
  DNUM INT,
  CONSTRAINT fk_DEPARTMENT
  FOREIGN KEY (DNUM)
  REFERENCES DEPARTMENT(DNUM)
  );

  ALTER TABLE DEPTLOCATION 
  ADD Location varchar (50);

  CREATE TABLE PROJECT (
  Pnum int PRIMARY KEY,
  Pname varchar (50),
  LOC varchar (50),
  DNUM INT,
  CONSTRAINT fk_DEPARTMENTP
  FOREIGN KEY (DNUM)
  REFERENCES DEPARTMENT(DNUM)
  );

  CREATE TABLE WORKON (
  SSN INT,
  CONSTRAINT fk_EMPLOYEE
  FOREIGN KEY (SSN)
  REFERENCES EMPLOYEE (SSN),

  Pnum INT,
  CONSTRAINT fk_PROJECT
  FOREIGN KEY (pnum)
  REFERENCES PROJECT (pnum),

  WH varchar (50)
  );


  CREATE TABLE DEPENDENT (
  Dname varchar (50) PRIMARY KEY,
  GN varchar (50),
  BD DATE NOT NULL,
  SSN INT,
  CONSTRAINT fk_EMPLOYEES
  FOREIGN KEY (SSN)
  REFERENCES EMPLOYEE (SSN)
  );

  ALTER TABLE EMPLOYEE
  ADD DNUM INT CONSTRAINT fk_DEPARTMENTE
  FOREIGN KEY (DNUM)
  REFERENCES DEPARTMENT(DNUM);

  ALTER TABLE EMPLOYEE
  ADD SUPERVISEDID INT CONSTRAINT fk_SUPERVISEDID
  FOREIGN KEY (SSN)
  REFERENCES EMPLOYEE(SSN);

  SELECT * FROM EMPLOYEE

  ALTER TABLE DEPARTMENT 
  ADD managerID INT CONSTRAINT fk_managerID
  FOREIGN KEY (DNUM)
  REFERENCES DEPARTMENT(DNUM);
  
  SELECT * FROM DEPARTMENT