CREATE DATABASE HOSPITAL
USE HOSPITAL 

CREATE TABLE PATIENT (
patID int PRIMARY KEY,
patName varchar(50),
gender varchar(20),
phone int NOT NULL,
DOB DATE,
bloodGroup varchar(20)
);

CREATE TABLE APPOINTMENT (
appoID int PRIMARY KEY,
Date DATE,
type VARCHAR(50),
time TIME,
status VARCHAR(50)
);

CREATE TABLE DOCTOR (
docID int PRIMARY KEY,
docName varchar(50),
specialization varchar(50),
phone int NOT NULL
);

CREATE TABLE SERVICEE (
namee VARCHAR(50),
type VARCHAR(50),
price int,

deptID INT,
CONSTRAINT fk_DEPARTMENT
FOREIGN KEY (deptID)
REFERENCES DEPARTMENT(deptID)
);

CREATE TABLE DEPARTMENT (
deptID int PRIMARY KEY,
deptName VARCHAR(50),

docID INT,
CONSTRAINT fk_DOCTOR
FOREIGN KEY (docID)
REFERENCES DOCTOR(docID)
);

CREATE TABLE RECORD (
diagnosis VARCHAR(50),
treatment VARCHAR(50),

patID INT,
CONSTRAINT fk_PATIENT
FOREIGN KEY (patID)
REFERENCES PATIENT(patID),

docID INT,
CONSTRAINT fk_DOCTORR
FOREIGN KEY (docID)
REFERENCES DOCTOR(docID)
);

SELECT * FROM RECORD

ALTER TABLE APPOINTMENT
ADD patID INT CONSTRAINT fk_PATIENTD
FOREIGN KEY (patID)
REFERENCES PATIENT(patID);

ALTER TABLE APPOINTMENT
ADD docID INT CONSTRAINT fk_DOCTORRS
FOREIGN KEY (docID)
REFERENCES DOCTOR(docID);

DROP TABLE SERVICEE